---
- name: deploy nginx.repo
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: install nginx
  yum:
    name: nginx
    state: latest
    enablerepo: nginx

- name: deploy local.conf
  template:
    src: local.conf
    dest: /etc/nginx/conf.d/local.conf
  notify: restart nginx

- name: launch nginx service
  service:
    name: nginx
    state: started
    enabled: yes
