---
- name: Deploy nginx.repo
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: Install nginx
  yum:
    name: nginx
    state: latest
    enablerepo: nginx

- name: Launch nginx service
  service:
    name: nginx
    state: started
    enabled: yes
