- name: Deploy nginx.repo
  template:
    src: yarn.repo
    dest: /etc/yum.repos.d/yarn.repo

- name: Install nginx
  yum:
    name: yarn
    state: latest
    enablerepo: yarn

- name: Install packages of the frontend related
  shell: yarn install
