- name: Copy template files
  template:
    src: 'mongodb-org.repo'
    dest: '/etc/yum.repos.d/mongodb-org.repo'

- name: Install mongodb
  yum:
    name: 'mongodb-org'
    state: present

- name: Execute mongo service
  service:
    name: mongod
    state: started
    enabled: yes
