- name: install yum package
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openssl-devel

- name: install python
  shell: |
    cd /usr/local/src
    wget https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
    tar zxvf Python-3.5.1.tgz
    cd  Python-3.5.1
    ./configure --prefix=/usr/local/bin/python-3.5.1
    make
    make install
    ln -s /usr/local/bin/python-3.5.1/bin/python3.5 /usr/local/bin/python3
    ln -s /usr/local/bin/python-3.5.1/bin/pip3 /usr/local/bin/pip3
