---
- name: check if you already have python installed
  command: python --version
  register: result
  changed_when: false
  ignore_errors: yes

- name: install python
  shell: |
    cd /usr/local/src
    wget https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tgz
    tar zxvf Python-3.5.1.tgz
    cd  Python-3.5.1
    ./configure --prefix=/usr/local/bin/python-3.5.1
    make
    make install
    unlink /usr/local/bin/python
    ln -s /usr/local/bin/python-3.5.1/bin/python3.5 /usr/local/bin/python
    ln -s /usr/local/bin/python-3.5.1/bin/pip /usr/local/bin/pip
  when: result.rc != 0 or result.stderr != "Python 3.5.1"
