- name: Install java
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present

- name: Download selenium
  get_url:
    url: http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
    dest: "{{ home_dir }}"

- name: Deploy selenium.service
  template:
    src: selenium.service
    dest: /etc/systemd/system/selenium.service

- name: Executed selenium service
  service:
    name: selenium
    state: started
    enabled: yes
