---
- name: Check mysql community rpm if exists
  command: rpm -q mysql57-community-release-el7-11.noarch
  register: result
  changed_when: false
  ignore_errors: yes

- name: Install mysql community rpm
  command: sudo rpm -Uvh http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
  when: result.stdout.find('mysql57-community-release-el7-11.noarch is not installed') != -1

- name: Installe mysql
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mysql-server
    - mysql-devel
    - MySQL-python
    - libselinux-python

- name: Execute mysqld service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Copy my.cnf
  template:
    src: .my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mysqld
