- name: Install create-react-app, forever, webpack
  npm:
    name: '{{ item }}'
    global: yes
  with_items:
    - express-generator
    - create-react-app
    - http-server
    - forever
    - webpack
  become: yes
  become_user: root
