- name: Install php7 relational modules
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - gcc-c++
    - autoconf
    - httpd-devel
    - zlib-devel
    - openssl-devel
    - gd-devel
    - libxml2-devel
    - mysql-devel
    - t1lib-devel
    - bzip2-devel
    - curl-devel
    - gmp-devel
    - aspell-devel
    - recode-devel
    - icu
    - libicu-devel
    - libmcrypt
    - libmcrypt-devel
    - php-intl

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install remi-release-7
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: Install php7
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: remi
    enablerepo: remi-php70
  with_items:
    - php
    - php-xml

- name: Install composer
  shell: |
    php -r "copy('https://getcomposer.org/installer', '/home/vagrant/selenium/composer-setup.php');"
    php -r "if (hash_file('SHA384', '/home/vagrant/selenium/composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('/home/vagrant/selenium/composer-setup.php'); } echo PHP_EOL;"
    php /home/vagrant/selenium/composer-setup.php --install-dir=/home/vagrant/selenium --filename=composer
    php -r "unlink('/home/vagrant/selenium/composer-setup.php');"
  become: yes
  become_user: vagrant
