---
- name: Import elasticsearch rpm
  command: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copy elasticsearch.repo template
  template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Copy kibana.repo template
  template:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana.repo

- name: Install elasticsearch and relational packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - java-1.8.0-openjdk.x86_64
    - elasticsearch
    - kibana

- name: Start elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Start kibana service
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy elasticsearch.yml template
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Copy kibana.yml template
  template:
    src: kibana.yml
    dest: /opt/kibana/config/kibana.yml
  notify: restart kibana

- name: Install plugin
  shell: |
    /usr/share/elasticsearch/bin/plugin install analysis-kuromoji
    /usr/share/elasticsearch/bin/plugin install analysis-icu
    /opt/kibana/bin/kibana plugin --install elastic/sense
  notify:
    - restart elasticsearch
    - restart kibana
