- name: Copy docker.repo
  template:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install docker
  yum:
    name: docker-engine
    state: present

- name: Start the docker service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker
    - docker-engine
