- name: Install yum packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - wget
    - git
    - tar
    - bind-utils
    - sysstat
    - zip
    - unzip
    - nc
    - lsof
    - perf

- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
