---
- name: install yum packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openssl-devel
    - glibc-headers
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel
    - bzip2

- name: check if you already have ruby installed
  command: /usr/local/bin/ruby --version
  register: result
  changed_when: false
  ignore_errors: yes

- name: install ruby
  shell: |
    yum remove -y ruby
    cd ~
    wget http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.gz
    tar xvfz ruby-2.3.0.tar.gz
    cd ruby-2.3.0
    ./configure
    make
    make install
  when: result.rc != 0

- name: install bundle and rails
  shell: |
    /usr/local/bin/gem install bundler
    /usr/local/bin/gem install rails
    /usr/local/bin/gem install unicorn

- name: check if you already have rails project
  stat:
    path: "{{ app_home_dir }}/{{ app_name }}"
  register: has_project

- name: create rails project
  shell: |
    cd '{{ app_home_dir }}'
    /usr/local/bin/rails new '{{ app_name }}'
  when: not has_project.stat.exists
