---
- name: install yum packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openssl-devel
    - glibc-headers
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel
    - bzip2

- name: check if you already have ruby installed
  command: /usr/local/bin/ruby --version
  register: result
  changed_when: false
  ignore_errors: yes

- name: install ruby
  shell: |
    yum remove -y ruby
    cd ~
    wget http://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.gz
    tar xvfz ruby-2.3.0.tar.gz
    cd ruby-2.3.0
    ./configure
    make
    make install
  when: result.rc != 0

- name: check if you already have bundler installed
  command: /usr/local/bin/bundler --version | grep bundler | grep -v bundler
  register: result
  changed_when: false
  ignore_errors: yes

- name: install bundler
  command: /usr/local/bin/gem install bundler
  when: result.rc != 0

- name: check if you already have rails installed
  command: /usr/local/bin/rails --version | grep rails | grep -v rails
  register: result
  changed_when: false
  ignore_errors: yes

- name: install rails
  command: /usr/local/bin/gem install rails
  when: result.rc != 0

- name: check if you already have rails project
  stat:
    path: '/var/www/{{ app_name }}/Gemfile'
  register: is_file

- name: create rails project
  shell: |
    cd /var/www
    /usr/local/bin/rails new '{{ app_name }}' -d mysql
  when: is_file.stat.md5 is not defined
