- name: Check if you already have rails project
  stat:
    path: '/var/www/{{ app_name }}/Gemfile'
  register: is_file

- name: Create new rails project
  shell: |
    cd /var/www/
    /usr/local/bin/rails new {{ app_name }} -d mysql
  when: is_file.stat.md5 is not defined

- name: Deploy Gemfile
  template:
    src: Gemfile
    dest: "/var/www/{{ app_name }}/Gemfile"
  become: yes
  become_user: vagrant

- name: Execute bundle install
  shell: |
    cd /var/www/{{ app_name }}
    /usr/local/bin/bundle install
  become: yes
  become_user: vagrant

- name: Deploy local.conf
  template:
    src: local.conf
    dest: /etc/nginx/conf.d/local.conf
  notify: restart nginx

- name: Deploy unicorn.rb
  template:
    src: unicorn.rb
    dest: '/var/www/{{ app_name }}/config/unicorn.rb'

- name: Change mode of /run
  file:
    path: /run
    mode: 0777

- name: Deploy unicorn.service
  template:
    src: unicorn.service
    dest: '/usr/lib/systemd/system/unicorn.service'

- name: Start unicorn service
  service:
    name: unicorn
    state: started
    enabled: yes
