---
- name: install yum packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openssl-devel
    - glibc-headers
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel
    - bzip2

- name: Deploy .bashrc for vagrant user
  template:
    src: .bashrc
    dest: ~/.bashrc
  become: yes
  become_user: vagrant

- name: Clone rbenv repository
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
    refspec: master:refs/remotes/origin/master
  become: yes
  become_user: vagrant

- name: Clone rbenv repository
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    refspec: master:refs/remotes/origin/master
  become: yes
  become_user: vagrant

- name: Edit secure path
  lineinfile: >-
    dest=/etc/sudoers
    state=present
    backrefs=yes
    regexp='^Defaults    secure_path*'
    line='Defaults    env_keep += "PATH"\nDefaults    env_keep += "RBENV_ROOT"'
